"""baseline_schema

Revision ID: 50b93e3fd628
Revises: 
Create Date: 2026-02-03 23:09:12.269072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b93e3fd628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='reconciliationrunstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_report_date'), 'reconciliation_runs', ['report_date'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'MISMATCH', 'MISSING', name='reconciliationitemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_payment_id'), 'reconciliation_items', ['payment_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_run_id'), 'reconciliation_items', ['run_id'], unique=False)
    op.add_column('payments', sa.Column('execute_idempotency_key', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('payments', sa.Column('executed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'payments', ['execute_idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'executed_at')
    op.drop_column('payments', 'retry_count')
    op.drop_column('payments', 'execute_idempotency_key')
    op.drop_index(op.f('ix_reconciliation_items_run_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_payment_id'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_runs_report_date'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    # ### end Alembic commands ###
