"""baseline_schema

Revision ID: cc4143af757c
Revises: effa41c5e07b
Create Date: 2026-03-01 21:07:59.308159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4143af757c'
down_revision: Union[str, Sequence[str], None] = 'effa41c5e07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('st_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('st_writeback_status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('st_writeback_error', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('st_written_back_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('amount_source', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('st_invoice_total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('st_invoice_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reconciliation_items', sa.Column('st_balance_expected', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reconciliation_items', sa.Column('st_balance_actual', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reconciliation_items', sa.Column('st_balance_match', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_items', 'st_balance_match')
    op.drop_column('reconciliation_items', 'st_balance_actual')
    op.drop_column('reconciliation_items', 'st_balance_expected')
    op.drop_column('payments', 'st_invoice_balance')
    op.drop_column('payments', 'st_invoice_total')
    op.drop_column('payments', 'amount_source')
    op.drop_column('payments', 'st_written_back_at')
    op.drop_column('payments', 'st_writeback_error')
    op.drop_column('payments', 'st_writeback_status')
    op.drop_column('payments', 'st_payment_id')
    # ### end Alembic commands ###
