"""baseline schema

Revision ID: f17912b5e0b7
Revises: 
Create Date: 2026-02-01 22:15:15.984498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17912b5e0b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('provider_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'provider_payment_id')
    op.drop_column('payments', 'provider')
    # ### end Alembic commands ###
